#! /bin/sh

bspc config border_width        1
bspc config window_gap          10

bspc monitor -d I II III IV V VI VII VIII IX X



bspc config top_padding 20

bspc config split_ratio         0.50
bspc config borderless_monocle  true
bspc config gapless_monocle     true
bspc config focus_follows_pointer true
bspc config auto_alternate true
bspc config auto_cancel true
bspc config normal_border_color "#332d29"
bspc config active_border_color "#817267"
bspc config focused_border_color "#504339"
bspc config presel_border_color "#9a875f"
bspc config urgent_border_color "#9f7155"
bspc config focused_locked_border_color "#9a875f"
bspc config normal_frame_opacity 0.0
bspc config focused_frame_opacity 0.1


bspc rule -a Skype pseudo_tiled=on
bspc rule -a Spotify pseudo_tiled=on
bspc rule -a Thunar pseudo_tiled=on
bspc rule -a Skype pseudo_tiled=on
bspc rule -a File-roller pseudo_tiled=on
bspc rule -a Transmission-gtk pseudo_tiled=on
bspc rule -a Conky sticky=on manage=off lower=on

bspc rule -a Gimp floating=on
bspc rule -a Chromium
bspc rule -a Screenkey manage=off


urxvt -e cava &
bspc rule -a urxvt split_ratio=0.5
urxvt -e ncmpcpp &
bspc rule -a urxvt split_ratio=0.5
urxvt -e weechat & 

dunst & 
pulseaudio-ctl &
compton --config ~/.compton.conf &
/home/ninjafruit/.config/bspwm/panel &

